"""initial schema

Revision ID: de031809e547
Revises: 
Create Date: 2026-07-29 15:49:27.691230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de031809e547'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('localisation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('branch_id')
    )
    op.create_table('stocks',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='check_stock_quantity'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('branch_id', 'product_id', name='uq_stock_branch_product')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('Common', 'Admin', name='role'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='userstatus'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(role = 'Admin' AND branch_id IS NULL) OR (role = 'Common' AND branch_id IS NOT NULL)"),
    sa.CheckConstraint("(status != 'Active' OR deleted_at IS NULL)"),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('stocks')
    op.drop_table('branches')
    # ### end Alembic commands ###
